CREATE TABLE products (
	id SMALLSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	kcal SMALLINT NOT NULL CHECK(kcal > 0)
);

CREATE TABLE food_diary(
	id SMALLSERIAL PRIMARY KEY,
	recording_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	product_id SMALLINT REFERENCES products (id) NOT NULL,
	amount SMALLINT NOT NULL CHECK(amount > 0)
);

CREATE TABLE cases(
	id SMALLSERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE case_diary(
	id SMALLSERIAL PRIMARY KEY,
	recording_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	case_id SMALLINT REFERENCES cases(id) NOT NULL
);